spring:
  application:
    name: ComplaintService
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Complaint_Service?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:ManasiP@123}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9092

eureka:
#  instance:
#    prefer-ip-address: true
  client:
#    fetch-registry: true
#    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
#spring:
#    application:
#      name: ComplaintService
#    datasource:
#      url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Complaint_Service?createDatabaseIfNotExist=true}
#      username: ${SPRING_DATASOURCE_USERNAME:root}
#      password: ${SPRING_DATASOURCE_PASSWORD:ManasiP@123}
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#      generate-ddl: true
#server:
#    port: 9092

