eureka:
  instance:
    hostname: localhost
  client:                  #    this will stop this project from being client
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
spring:
  application:
    name: ServiceRegistry