server:
  port: 9093
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: UserService
            uri: lb://UserService
            predicates:
              - Path=/register/**,/login/**,/add/**,/citizen/**

          - id: ComplaintService
            uri: lb://ComplaintService
            predicates:
              - Path=/complaint/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka